-- MySQL Script generated by MySQL Workbench
-- ter 14 fev 2023 17:13:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `prontuario` VARCHAR(15) NOT NULL,
  `nome` TEXT(50) NOT NULL,
  `data_nascimento` DATE NULL,
  `genero` CHAR(1) NOT NULL DEFAULT 'N',
  `etinia` FLOAT NULL DEFAULT 'NÃO DEFINIDO',
  `altura` FLOAT NULL DEFAULT F,
  `peso` VARCHAR(45) NULL,
  PRIMARY KEY (`prontuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `codigo` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `aluno_prontuario` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turma` (
  `codigo` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(100) NULL,
  `semestre` TINYINT(30) NULL,
  `ano` YEAR(4) NULL,
  `professor` VARCHAR(100) NULL,
  `aluno_prontuario` VARCHAR(15) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`disciplina` (
  `codigo` VARCHAR(15) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `aluno_prontuario` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pre_requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pre_requisito` (
  `numero_requisitos` INT NOT NULL,
  `numero_diciplina` VARCHAR(45) NULL,
  `disciplina_codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`numero_requisitos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
